### ISSUE TITLE
Call to undefined function base_url()

### ISSUE THREAD

**Issue by bytecodedhawal** [anburocky3/Latest-Codeigniter-3.1.5-HMVC-Modules#1]
Call to undefined function base_url()
why this error occur ??????????????????/

**Comment by SamWatsonOrSomething** [comment]
Hi @bytecodedhawal, I'd guess that the URL helper isn't being loaded - you need the following line in your controller:

`$this->load->helper('url');
`

Hopefully that should solve the problem!

**Comment by anburocky3** [comment]
> Call to undefined function base_url()
> why this error occur ??????????????????/

Yes, please make sure you loaded the URL helper in your blocks. Please check @SamWatsonOrSomething  post for more info.
